### PR TITLE
fix(style): improve output messaging

### LINKED ISSUE #39: cleanup tool messaging output
it looks gross right now

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #39, #44, #46

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -32,18 +46,57 @@ enum Command {
...
+        );
         manifest::write_package_json(&crate_path)?;
+        println!(
+            "{} {}Copying over your README...",
+            style("[5/7]").bold().dim(),
+            DANCERS
+        );
         readme::copy_from_crate(&crate_path)?;
+        println!(
+            "{} {}Installing WASM-bindgen...",
```
Comment (mgattozzi) [inline src/main.rs]: Maybe we can make this an optional thing at some point? like if it's installed we just do 6 things rather than 7. But that's like a future improvement and not something that needs to be done now and block 0.1

**Comment by mgattozzi** [comment]
This is all very nice and much easier to see where things are happening :D

File: src/main.rs (hunk 1 above)
Comment (ashleygwilliams) [reply src/main.rs]: so currently, if wasm-bindgen is already installed this step doesn't actually do anything (it actually fails and yells in stderr). we should def check if it's installed and just skip if it is... both this and adding the target should just not happen if they are already present.

Comment (mgattozzi) [reply src/main.rs]: In which case the numbering will also need to be dynamically done rather than it being hardcoded. Maybe a step at the beginning to calculate what can be done without then run the rest.
